# Generated by Django 2.2.1 on 2019-05-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0007_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='nick', max_length=150),
        ),
    ]
