# Generated by Django 2.2.1 on 2019-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0008_auto_20190527_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='x515692@nwytg.net', max_length=150),
        ),
    ]
