# Generated by Django 2.2.1 on 2019-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0009_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345678', max_length=150),
        ),
    ]
