# Generated by Django 2.2.1 on 2019-07-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0012_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='Empty', max_length=1024),
        ),
    ]
