# Generated by Django 2.2 on 2019-07-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0013_reservation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='googleId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='I want to reserve this room because: ', max_length=1024),
        ),
    ]
