# Generated by Django 2.2.1 on 2019-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0014_auto_20190706_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
