# Generated by Django 2.2 on 2019-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='I want to book this room because: ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Accepted'), ('r', 'Rejected'), ('i', 'In Progress')], help_text='Reservation status', max_length=1),
        ),
    ]
