# Generated by Django 2.2.4 on 2019-08-29 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular Reservation', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'Accepted'), ('r', 'Rejected'), ('i', 'In Progress')], help_text='Reservation status', max_length=1)),
                ('description', models.CharField(default='I want to book this room because: ', max_length=1024)),
                ('start_reservation', models.DateTimeField(blank=True, null=True)),
                ('end_reservation', models.DateTimeField(blank=True, null=True)),
                ('googleId', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.Room')),
            ],
        ),
    ]
